### PR TITLE
[#74] Generated decoders for unit type does not compile

### LINKED ISSUE #74: Generated decoders for unit type does not compile
Given the following Haskell types:

```haskell
data Foo = Foo ()
    deriving stock (Show, Generic)
    deriving anyclass (Eq, Ord, Hashable)
    deriving (Elm, ToJSON, FromJSON) via ElmStreet Foo

data Bar = Bar () Int
    deriving stock (Show, Generic)
    deriving anyclass (Eq, Ord, Hashable)
    deriving (Elm, ToJSON, FromJSON) via ElmStreet Bar
```

the following elm code is generated:

```elm

-- Types.elm
type Foo
    = Foo ()

type Bar
    = Bar () Int

-- decoder.elm
decodeFoo : Decoder Foo
decodeFoo =
    let decide : String -> Decoder Foo
        decide x = case x of
            "Foo" -> D.field "contents" <| D.map Foo (D.hardcoded ())
            c -> D.fail <| "Foo doesn't have such constructor: " ++ c
    in D.andThen decide (D.field "tag" D.string)

decodeBar : Decoder Bar
decodeBar =
    let decide : String -> Decoder Bar
        decide x = case x of
            "Bar" -> D.field "contents" <| D.map2 Bar (D.index 0 (D.hardcoded ())) (D.index 1 D.int)
            c -> D.fail <| "Bar doesn't have such constructor: " ++ c
    in D.andThen decide (D.field "tag" D.string)


```

This fails to compile with the following error message:

```
The 2nd argument to `map` is not what I expect:

145|             "Foo" -> D.field "contents" <| D.map Foo (D.hardcoded ())
                                                           ^^^^^^^^^^^^^^
This `hardcoded` call produces:

    Decoder (() -> b) -> Decoder b

But `map` needs the 2nd argument to be:

    Decoder ()
```

### PR DESCRIPTION
**Pull request by vrom911**
Resolves #74

The problem with unit type is fix, however there is some other problem after the previous PR.
I'm clueless, I've been debugging this whole morning, but can't get why this happening: when making the POST request for `OneType` it fails with the error:

```
Error in $: parsing Types.OneType failed, key "tag" not present
```

I checked each field, seems it's not working with each of them, so I have no idea, why. Seems like the previous PR changed more than expected.

### CODE REVIEW

**Comment by chshersh** [comment]
I have no idea why this doesn't work...

**Comment by vrom911** [comment]
So, I'm still trying to debug it. Here is what I do. I have this `OneType`. I create the value on elm part:

```elm
oneType : OneType
oneType =
    { prims =
        { unit = ()
        , bool = True
        , char = 'a'
        , int = 42
        , float = 42.5
        , string = "String"
        -- , time : Posix
        , maybe = Just 99
        , result = Ok "asd"
        , pair = ('b', False)
        , list = [1,2,3,4]
        }
    , myUnit = MyUnit ()
    , id = Id "id"
    , age = Age 11
    , requestStatus = Approved
    , user =
        { id = Id "user"
        , name = "user"
        , age = Age 18
        , status = Rejected
        }
    , guests = []
    , userRequest =
        { ids = [Id "1", Id "2"]
        , limit = 100
        , example = Nothing
        }
    }
```
Then I try to encode it on Elm part and decode on Haskell:

ELM:
```elm
> Json.Encode.encode 0 <| Core.Encoder.encodeOneType <| Core.Types.oneType
"{\"prims\":{\"unit\":[],\"bool\":true,\"char\":\"a\",\"int\":42,\"float\":42.5,\"string\":\"String\",\"maybe\":99,\"result\":{\"Right\":\"asd\"},\"pair\":[\"b\",false],\"list\":[1,2,3,4]},\"myUnit\":{\"tag\":\"MyUnit\",\"contents\":[]},\"id\":\"id\",\"age\":11,\"requestStatus\":\"Approved\",\"user\":{\"id\":\"user\",\"name\":\"user\",\"age\":18,\"status\":\"Rejected\"},\"guests\":[],\"userRequest\":{\"ids\":[\"1\",\"2\"],\"limit\":100,\"example\":null}}"
    : String
```

HASKELL:
```haskell
> A.eitherDecode @OneType "{\"prims\":{\"unit\":[],\"bool\":true,\"char\":\"a\",\"int\":42,\"float\":42.5,\"string\":\"String\",\"maybe\":99,\"result\":{\"Right\":\"asd\"},\"pair\":[\"b\",false],\"list\":[1,2,3,4]},\"myUnit\":{\"tag\":\"MyUnit\",\"contents\":[]},\"id\":\"id\",\"age\":11,\"requestStatus\":\"Approved\",\"user\":{\"id\":\"user\",\"name\":\"user\",\"age\":18,\"status\":\"Rejected\"},\"guests\":[],\"userRequest\":{\"ids\":[\"1\",\"2\"],\"limit\":100,\"example\":null}}"
Left
 "Error in $: parsing Types.OneType failed, key \"tag\" not present"
```

Still got that error, now I see what JSON is generated but I don't see any issues in it...

**Comment by vrom911** [comment]
Okay, so it seems that we need to pass `tag: ConstructorName` in every single type now to make one-constructor types work. I propose to do this separately, as the issue with unit type is resolved here and it's not related to the problems we encounter now.

**Comment by chshersh** [comment]
@vrom911 I agree with this solution. This PR can be merged and the issue can be resolved separately.

**Pull request merged**
