### PR TITLE
Include GHC 8.8.4 and 8.10.2 in .travis.yml

### PR DESCRIPTION
**Pull request by jhrcek**
Let's be a bit more future-proof before releasing to hackage.

### CODE REVIEW

**Comment by turboMaCk** [comment]
in some of my projects I've ran into issues with latest ghc versions on travis. Sadly I think it might not be well supported:/

**Comment by jhrcek** [comment]
@arbus can you please check/merge? I think it will be more future proof to relase 1.0.3 with these changes included, so we don't have to bump when upgrading to newer GHC/servetn.

**Comment by turboMaCk** [comment]
oh nice, you make it work for ghc 8.10!

**Review by arbus — APPROVED** [review]
👍 , thank you for bumping this

**Pull request merged**
