### PR TITLE
Support Json.Decode.Value as primitive

### PR DESCRIPTION
**Pull request by jhrcek**
An attempt to address https://github.com/Holmusk/elm-street/issues/111

### CODE REVIEW

**Comment by turboMaCk** [comment]
are you sure this would work when used in declaration? Types module does not import `Json.Decode/Encode` so `Value` type is not defined within that module https://github.com/Holmusk/elm-street/blob/cd9df51812c6bba0b9a7fb2ec4c421bba0ccaf61/src/Elm/Generate.hs#L121-L126

**Comment by jhrcek** [comment]
Not sure it you're looking at all the commits in this PR.
I added that import there:
https://github.com/Holmusk/elm-street/pull/114/files#diff-77e5a196b2b19636b3c11a33250006be287ea3155cc947a6866aba5583221d24R126

**Comment by turboMaCk** [comment]
ah sorry I indeed was looking on just the first commit - I had this tab opened for few days :face_with_head_bandage:

**Review by turboMaCk — APPROVED** [review]
LGTM

**Comment by copytypecat** [comment]
this is the first elm street PR, I'm looking into, so maybe this question is silly---but where is the logic for how a `Value` term in `.hs` gets converted to a `Value` term in `.elm`?

**Comment by jhrcek** [comment]
There is no need for explicit logic for converting `Aeson.Value` to elm's `Json.Decode.Value`.

`Aeson.Value` is Haskell representation of json AST.
Aeson encoding works like this:
`YourDataType` -- [toJson](https://hackage.haskell.org/package/aeson-1.5.6.0/docs/Data-Aeson-Types.html#v:toJSON) --> `Aeson.Value` -- [encode](https://hackage.haskell.org/package/aeson-1.5.6.0/docs/Data-Aeson.html#v:encode) --> `ByteString`.

The first arrow is taken care of ToJSON instance for `YourDataType`.
In the case of value the instance of ToJSON is [trivial](https://hackage.haskell.org/package/aeson-1.5.6.0/docs/src/Data.Aeson.Types.ToJSON.html#line-1973).

The second arrow is about serializing Value to sequence of Bytes (ByteString) which are then sent over the network.
In our case this is taken care of for us by servant's [mimeRender](https://hackage.haskell.org/package/servant-0.18.2/docs/src/Servant.API.ContentTypes.html#line-332) which is just calling aeson's [encode](https://hackage.haskell.org/package/aeson-1.5.6.0/docs/Data-Aeson.html#v:encode).

From the point of view of `elm/json` library, [Value](https://package.elm-lang.org/packages/elm/json/latest/Json-Decode#Value) is an opaque data type. It's Elm representation of json AST. Elm gives you primitive decoder [value](https://package.elm-lang.org/packages/elm/json/latest/Json-Decode#value) which I'm using for [any field with this type](https://github.com/Holmusk/elm-street/pull/114/files#diff-e00ea89d2cfdec9165ef4eca8ca599cdfa13711b70c9e6dc924b4a79c572961e).
Maybe looking at https://hackage.haskell.org/package/elm-street-0.1.0.4/docs/src/Elm.Ast.html will make things clearer. Basically data types are like trees with primitives at the leaves. On elm side primitives are decoded by decoders provided by elm/json, so they don't requires us to generate decoders.

Is that clear enough?

**Comment by jhrcek** [comment]
@copytypecat btw as a learning project I highly recommend going through/understanding all the source code of this project.
It's relatively small (just ~1000 lines of code) with lots of interesting Haskell used. And feel free to spam me with questions about it.

**Pull request merged**
